Dev-307 Adapt middleware deployment script for testnet
eodata/middleware pull request #15
Opened 2024-03-11 22:08 UTC by yonikesel1

1. Restructure deployment folders
2. Added deployment config
3. Added sanity checks after deployment

2024-03-12 08:01 UTC, RonTuretzky requested changes

2024-03-12 08:01 UTC, RonTuretzky commented on script/deploy/goerli/Goerli_DeployEOMiddlewareContracts.s.sol
> +    uint256 numStrategies = deployedStrategyArray.length;
I don't understand how this is a legal line lol , where is deployedStrategyArray defined?

2024-03-12 08:01 UTC, RonTuretzky commented on test/integration/tests/DeployEOMiddlewareContracts.t.sol
> +    address public EORACLE_OWNER = 0xeA96Fa8F6a185D6B97eCDeb9805178F6C2829eeE;
this should be changed to 0x119156A81E4f3d891cBd106a4AedEA916A0A9C4b as we stopped using the Ae96 account outside of local deploy

2024-03-12 08:01 UTC, RonTuretzky requested changes

2024-03-12 08:01 UTC, RonTuretzky commented on test/integration/tests/DeployEOMiddlewareContracts.t.sol
> +    address public EORACLE_OWNER = 0xeA96Fa8F6a185D6B97eCDeb9805178F6C2829eeE;
```suggestion
    address public EORACLE_OWNER = 0x119156A81E4f3d891cBd106a4AedEA916A0A9C4b;
```

2024-03-12 09:20 UTC, yonikesel1 commented on script/deploy/goerli/Goerli_DeployEOMiddlewareContracts.s.sol
> +    uint256 numStrategies = deployedStrategyArray.length;
deployedStrategyArray is defined in ExistingDeploymentParser.sol.
But, numStrategies is not used here so removing it.

2024-03-12 09:25 UTC, yonikesel1 commented on test/integration/tests/DeployEOMiddlewareContracts.t.sol
> +    address public EORACLE_OWNER = 0xeA96Fa8F6a185D6B97eCDeb9805178F6C2829eeE;
done

2024-03-12 09:25 UTC, yonikesel1 commented on test/integration/tests/DeployEOMiddlewareContracts.t.sol
> +    address public EORACLE_OWNER = 0xeA96Fa8F6a185D6B97eCDeb9805178F6C2829eeE;
done

2024-03-12 11:18 UTC, RonTuretzky approved these changes

2024-03-13 14:28 UTC, ArielLaub approved these changes

2024-03-13 17:26 UTC, merged